logging:
  config: classpath:logback-spring.xml
  directory: ./logs
  level:
    root: debug

brpc:
  global:
    naming:
      namingServiceUrl: consul://127.0.0.1:8500
      group: "normal"
      version: 2.0.0
      ignoreFailOfNamingService: false
      extra:
        - key: weight
          value: 10
    server:
      port: 8002
      workThreadNum: 1
      ioThreadNum: 1
      interceptorBeanNames: customInterceptor,customInterceptor2